#Linux only
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
  pvws:
    build: ./pvws/docker
    network_mode: host
  server:
    build: ./server
    network_mode: host
  qserver:
    build: ./server/queue-server-configuration
    network_mode: host
  httpserver:
    build: ./server/queue-server-configuration/httpserver
    network_mode: host