#Mac or Linux

## to do: volume mount the frontend files to a container, put in docker.dev. in frontend that just calls npm start
services:
  epics:
    image: prjemian/synapps:latest
    platform: linux/amd64
    networks:
      - epicsnet
    command: /bin/bash
    tty: true
    stdin_open: true
  pvws:
    build: ./pvws/docker
    ports:
      - "8080:8080"
    networks:
      - epicsnet
  server:
    build: ./server
    ports:
      - "8000:8000"
      - "8888:8888"
    networks:
      - epicsnet

networks:
  epicsnet:
    driver: bridge